import = [
  "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 11.0
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[scrolling]
history = 10000

[window]
opacity = 1.0
padding = { x = 3, y = 3 }
# dimensions = { columns = 80, lines = 20 }
decorations = "None"
dynamic_title = true

[cursor]
# smooth_motion = true
# smooth_motion_factor = 0.6
style = { shape = "Beam", blinking = "Never" }
vi_mode_style = { shape = "Beam", blinking = "Never" }
# blink_interval = 600
# blink_timeout = 0
thickness = 0.2
unfocused_hollow = false
